### ISSUE TITLE
Goto Declaration can result in an error logged when it is used on symbols defined with no source code.

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fsharpbinding#556]
I believe this is because `Filename` is `null` in the NRefactory definition that we build.
```
ERROR [2014-05-17 21:25:00Z]: FileName == null
   at System.Environment.get_StackTrace() in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/corlib/System/Environment.cs:line 261
   at MonoDevelop.Ide.Gui.FileOpenInformation.set_FileName(FilePath value) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs:line 1179
   at MonoDevelop.Ide.Gui.FileOpenInformation..ctor(FilePath filePath, MonoDevelop.Projects.Project project) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs:line 1203
   at MonoDevelop.Ide.Gui.Workbench.OpenDocument(FilePath fileName, MonoDevelop.Projects.Project project, Int32 line, Int32 column, OpenDocumentOptions options, System.Text.Encoding encoding, IViewDisplayBinding binding) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs:line 421
   at MonoDevelop.Ide.Gui.Workbench.OpenDocument(FilePath fileName, MonoDevelop.Projects.Project project, Int32 line, Int32 column, OpenDocumentOptions options) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs:line 411
   at MonoDevelop.Ide.ProjectOperations.JumpToDeclaration(INamedElement element) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs:line 291
   at MonoDevelop.Ide.ProjectOperations.JumpToDeclaration(INamedElement visitable, Boolean askIfMultipleLocations) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs:line 267
   at MonoDevelop.Refactoring.GotoDeclarationHandler.Run(System.Object data) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/GotoDeclarationHandler.cs:line 51
   at MonoDevelop.Components.Commands.CommandHandler.InternalRun(System.Object dataItem) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandHandler.cs:line 42
   at MonoDevelop.Components.Commands.CommandManager.DefaultDispatchCommand(MonoDevelop.Components.Commands.ActionCommand cmd, MonoDevelop.Components.Commands.CommandInfo info, System.Object dataItem, System.Object target, CommandSource source) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:line 1045
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(System.Object commandId, System.Object dataItem, System.Object initialTarget, CommandSource source) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:line 1012
   at MonoDevelop.Components.Commands.CommandManager.DispatchCommand(System.Object commandId, CommandSource source) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:line 850
   at MonoDevelop.Components.Commands.CommandManager.OnKeyPressed(System.Object o, Gtk.KeyPressEventArgs e) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs:line 362
   at System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod , System.Object , System.Object[] , System.Exception ByRef )
   at System.Reflection.MonoMethod.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/corlib/System.Reflection/MonoMethod.cs:line 230
   at System.Reflection.MethodBase.Invoke(System.Object obj, System.Object[] parameters) in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/corlib/System.Reflection/MethodBase.cs:line 114
   at System.Delegate.DynamicInvokeImpl(System.Object[] args) in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/corlib/System/Delegate.cs:line 424
   at System.MulticastDelegate.DynamicInvokeImpl(System.Object[] args) in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/corlib/System/MulticastDelegate.cs:line 70
   at System.Delegate.DynamicInvoke(System.Object[] args) in /Volumes/build-root-ramdisk/mono-3.4.0/mcs/class/corlib/System/Delegate.cs:line 398
   at GLib.Signal.ClosureInvokedCB(System.Object o, GLib.ClosureInvokedArgs args) in /Volumes/build-root-ramdisk/gtk-sharp-2.12.21/glib/Signal.cs:line 195
   at GLib.SignalClosure.Invoke(GLib.ClosureInvokedArgs args) in /Volumes/build-root-ramdisk/gtk-sharp-2.12.21/glib/SignalClosure.cs:line 118
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) in /Volumes/build-root-ramdisk/gtk-sharp-2.12.21/glib/SignalClosure.cs:line 159
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run() in /Volumes/build-root-ramdisk/gtk-sharp-2.12.21/gtk/Application.cs:line 135
   at MonoDevelop.Ide.IdeApp.Run() in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs:line 383
   at MonoDevelop.Ide.IdeStartup.Run(MonoDevelop.Ide.MonoDevelopOptions options) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:line 300
   at MonoDevelop.Ide.IdeStartup.Main(System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) in /Users/builder/data/lanes/886/89cfcdd2/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:line 620
   at Xamarin.Startup.MainClass.Main(System.String[] args) in /Users/builder/data/lanes/886/89cfcdd2/source/md-addins/Xamarin.Startup/Main.cs:line 11
 
```

**Comment by 7sharp9** [comment]
Fixed in FSharpMDXS
