### ISSUE TITLE
Unhandled exception from FCS while browsing tools/docs/generate.fsx

### ISSUE THREAD

**Issue by rneatherway** [fsharp/fsharpbinding#777]
```
Unhandled Exception: Microsoft.FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange: Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange' was thrown.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at FSharp.InteractiveAutocomplete.Main.main(State state) in D:\dev\rneatherway-fsharpbinding\FSharp.AutoComplete\Program.fs:line 493
   at FSharp.InteractiveAutocomplete.Main.entry(String[] args) in D:\dev\rneatherway-fsharpbinding\FSharp.AutoComplete\Program.fs:line 569
```

**Comment by rneatherway** [comment]
This issue was moved to fsharp/FSharp.AutoComplete#19
